# Generated by Django 5.0 on 2023-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_more1_more2_servises1_servises2_servises3_servises4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='more3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='pageup',
        ),
    ]
