# Generated by Django 5.0 on 2023-12-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_more3_delete_pageup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='img',
        ),
    ]
