# Generated by Django 5.0 on 2023-12-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_remove_weblog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ostads',
            name='img',
        ),
    ]
